/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { PerspectiveCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/rG4M8Lh9tjdZQe50/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#5e6063"]} />
      <group {...props} dispose={null}>
        <mesh
          name="Pyramid 2"
          geometry={nodes["Pyramid 2"].geometry}
          material={nodes["Pyramid 2"].material}
          castShadow
          receiveShadow
          position={[-1424.73, 0, 1061.37]}
        />
        <mesh
          name="Pyramid"
          geometry={nodes.Pyramid.geometry}
          material={materials["Pyramid Material"]}
          castShadow
          receiveShadow
          position={[-2423.42, 0, 925.56]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[200, 300, 300]}
        />
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={5}
          fov={45}
          position={[-2591.35, 682.87, 1829.14]}
          rotation={[-0.78, -0.11, -0.11]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </>
  );
}
